server:
  port: 88
  ssl:
    enabled: false
logging:
  level:
    com.java993: INFO
spring:
  redis:
    host: localhost
    port: 6379
  profiles:
    active: local
telegram:
  bot:
    commands: classpath:commands.json
news:
  checker:
    job:
      initialDelay: 1000
      #fixedDelay: 300000
      fixedDelay: 5000